alertmanager:
  enabled: false
coreDns:
  enabled: false
defaultRules:
  create: false
  rules:
    alertmanager: false
    etcd: false
    general: false
    k8s: false
    kubeApiserver: false
    kubePrometheusNodeAlerting: false
    kubePrometheusNodeRecording: false
    kubeScheduler: false
    kubernetesAbsent: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    node: false
    prometheus: false
    prometheusOperator: false
grafana:
  service:
    type: LoadBalancer
  plugins:
  - petrslavotinek-carpetplot-panel
  - michaeldmoore-multistat-panel
  - neocat-cal-heatmap-panel
  - ryantxu-ajax-panel
  - grafana-piechart-panel
  - grafana-clock-panel
  - aidanmountford-html-panel
  - simpod-json-datasource
  image:
    repository: grafana/grafana
    tag: 7.2.0
  additionalDataSources:
  adminPassword: prom-operator
  enabled: true
  extraConfigmapMounts:
  - configMap: notifiers-configmap
    mountPath: /etc/grafana/provisioning/notifiers
    name: notifiers-configmap
    readOnly: true
  grafana.ini:
    auth.anonymous:
      enabled: true
      path: img/
    log:
      filters: ldap:debug
      level: error
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      annotations: {}
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
kubeApiServer:
  enabled: true
kubeControllerManager:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubeStateMetrics:
  enabled: false
kubelet:
  enabled: false
nodeExporter:
  enabled: false
prometheus:
  ingress:
    enabled: true
