# Service Accounts create dynamic secrets with API token.  Cert-Manager Kube-Auth requires the secret name to be used in the Auth configuration
#   To support linking dynamic creation of these services, overriding the SA creation from the helm chart and statically setting the secret name
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
secrets:
- name: cert-manager-token